### ISSUE TITLE
imply `$tx_state`

### ISSUE THREAD

**Issue by egasimus** [hackbg/fadroma#1]
* `$tx_state` is local to generated handler functions. Moving [the `ok!` macro definition](https://github.com/hackbg/fadroma/blob/main/rs/lib.rs#L222) into [the handler function template](https://github.com/hackbg/fadroma/blob/main/rs/lib.rs#L248) allows `ok!(...)` to be used instead of `ok!(state,...)`.
* Currently, the form `ok!(_,...)` means "success, no state updates necessary". This feature is not used by anyone yet, and if comparing 2 `$State` objects is cheaper than writing the same `$State` object, then this enhancement would benefit adding such a comparison [instead of this](https://github.com/hackbg/fadroma/blob/main/rs/lib.rs#L206) to avoid saving unchanged `$State` objects.

**Comment by mradkov** [comment]
Ok, as I see:
- `ok!(state,...)` - allows you to update the state
- `ok!(_,...)` - proceed with no state updates

So if this gets implemented and you solely use `ok!(...)`  how is the state getting updated in case you need it?

**Comment by egasimus** [comment]
If that gets implemented, the state would *always* get updated. The contract author just wouldn't need to specify it in the default case (returning `ok!()` would tell `fadroma` to save the state.)

There's one chief question that I ran into, which needs to be addressed in order to decide the most reasonable possible default behavior:

**Should short-circuits caused by the `?` operator save the state by default?** Or should handlers act similar to DB transactions and "revert" (i.e. ignore state changes on error by default?)
* Example [here](https://github.com/hackbg/sienna-secret-token/blob/wip/mgmt/src/lib.rs#L203): in that particular case, if serialization in `transfer_msg` fails, `state` is not saved, which is not obvious because the fact that `state` is just a local mutable copy to be auto-saved later is hidden from the user.
* Does it even make sense to save the state from anywhere else other than [the end of the handler](https://github.com/hackbg/fadroma/blob/main/rs/lib.rs#L206)?
* Does the contract author need to be able to explicitly say "don't save the state" (as currently possible with `ok!(_,...)`) outside of error conditions?
* Is checking the state object for changes efficient?

**Comment by egasimus** [comment]
possibly invalidated by #4 which would replace atomic full-state updates with explit imperative individual updates to values of state keys

**Comment by egasimus** [comment]
decided by https://github.com/hackbg/fadroma/commit/a1a560d8cd668878321e6a82b1ccdca4cda0cdc2 - saving state from a transaction needs to be explicit
