### ISSUE TITLE
Research SGX emulation

### ISSUE THREAD

**Issue by mradkov** [hackbg/fadroma#27]
We find ourselves in the need of simulating the SGX environment (at least for implementing automated test runners).

**Comment by htunlogic** [comment]
I believe I have managed to get this working now in the github action. Next step is to roll out the whole process of testing also the Rust part of the contract.

So far, only issue I have gotten is that in `test/contract/Cargo.toml` I had to use git to get Fadroma as dependency. When I do it through path it cannot find it in the container (obviously).

**Comment by htunlogic** [comment]
I have resolved the issue with linking Rust dependencies in integration tests. Also I have added unit tests for the example contract.

**Comment by mradkov** [comment]
> I have resolved the issue with linking Rust dependencies in integration tests. Also I have added unit tests for the example contract.
> 
> Please let me know if that is what you had in mind to be implemented.

Not exactly.

We want to have the ability to simulate SGX (secure enclave) execution environment (the one that is used in Secret Network) in a CI pipeline, so we can automate integration tests and procedures.

**Comment by egasimus** [comment]
With [this binding](https://github.com/hackbg/fadroma/blob/21.07/scrt-contract/contract_binding.rs#L54) SGX emulation is no longer necessary to run integration tests.
